version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      testing:
        patterns:
          - "jest*"
          - "ts-jest"
      typescript:
        patterns:
          - "typescript"
    ignore:
      - dependency-name: "typescript"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"